import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'social_model.dart';

class SocialLists {
  static List<SocialModel> socialList = [
    SocialModel('WhatsApp',
        icon: FontAwesomeIcons.whatsapp, colour: Colors.teal.shade800),
    SocialModel('Phone',
        icon: FontAwesomeIcons.phoneAlt, colour: Color(0xFF38A45B)),
    SocialModel('Telegram',
        icon: FontAwesomeIcons.telegram, colour: Colors.blue.shade800),
    SocialModel('Twitter',
        icon: FontAwesomeIcons.twitter, colour: Color(0xFF1da1f2)),
    SocialModel('Instagram',
        icon: FontAwesomeIcons.instagram, colour: Colors.orange.shade700),
    SocialModel('Tiktok',
        icon: FontAwesomeIcons.tiktok, colour: Color(0xFFEE1D52)),
    SocialModel('Sms', icon: FontAwesomeIcons.sms, colour: Color(0xFFDC722B)),
    SocialModel('Email', icon: FontAwesomeIcons.at, colour: Color(0xFFBB001B)),
    SocialModel('YouTube',
        icon: FontAwesomeIcons.youtube, colour: Color(0xFFF80000)),
    SocialModel('Google',
        icon: FontAwesomeIcons.google, colour: Color(0xFFE34133)),
    SocialModel('Github',
        icon: FontAwesomeIcons.github, colour: Color(0xFF211F1F)),
    SocialModel('Facebook',
        icon: FontAwesomeIcons.facebookF, colour: Color(0xFF4267B2)),
    SocialModel('Messenger',
        icon: FontAwesomeIcons.facebookMessenger, colour: Color(0xFF006AFF)),
    SocialModel('WeChat',
        icon: FontAwesomeIcons.weixin, colour: Color(0xFF7bb32e)),
    SocialModel('LinkedIn',
        icon: FontAwesomeIcons.linkedin, colour: Colors.blue.shade900),
    SocialModel('GooglePlay',
        icon: FontAwesomeIcons.googlePlay, colour: Color(0xFF40916c)),
    SocialModel('AppStore ',
        icon: FontAwesomeIcons.appStore, colour: Color(0xFF1F7EF4)),
    SocialModel('Paypal',
        icon: FontAwesomeIcons.paypal, colour: Color(0xff00457C)),
    SocialModel('Patreon',
        icon: FontAwesomeIcons.patreon, colour: Color(0xFFFF424D)),
    SocialModel('Stripe',
        icon: FontAwesomeIcons.stripeS, colour: Color(0xFF4379FF)),
    SocialModel('Amazon',
        icon: FontAwesomeIcons.amazon, colour: Color(0xFFFF9900)),
    SocialModel('Snapchat',
        icon: FontAwesomeIcons.snapchatGhost, colour: Colors.black),
    SocialModel('Medium',
        icon: FontAwesomeIcons.mediumM, colour: Color(0xFF000000)),
    SocialModel('Pinterest',
        icon: FontAwesomeIcons.pinterestP, colour: Color(0xFFE60023)),
    SocialModel('WeChat',
        icon: FontAwesomeIcons.weixin, colour: Color(0xFF7bb32e)),
    SocialModel('Devto', icon: FontAwesomeIcons.dev, colour: Color(0xFF000000)),
    SocialModel('Slack',
        icon: FontAwesomeIcons.slack, colour: Color(0xFF4A154B)),
    SocialModel('Twitch',
        icon: FontAwesomeIcons.twitch, colour: Color(0xFF6441A4)),
    SocialModel('Gitlab',
        icon: FontAwesomeIcons.gitlab, colour: Color(0xFFF46A25)),
    SocialModel('Discord',
        icon: FontAwesomeIcons.discord, colour: Color(0xFF7289DA)),
    SocialModel('Dribbble',
        icon: FontAwesomeIcons.dribbble, colour: Color(0xFFE34A85)),
    SocialModel('Steam',
        icon: FontAwesomeIcons.steam, colour: Color(0xFF2a475e)),
    SocialModel('Tumblr',
        icon: FontAwesomeIcons.tumblr, colour: Color(0xFF35465C)),
    SocialModel('Behance',
        icon: FontAwesomeIcons.behance, colour: Color(0xFF1666F7)),
    SocialModel('Blog', icon: FontAwesomeIcons.blog, colour: Color(0xFF087E8B)),
    SocialModel('Blog2',
        icon: FontAwesomeIcons.penAlt, colour: Color(0xFF087E8B)),
    SocialModel('GeneralWebsite',
        icon: FontAwesomeIcons.globe, colour: Colors.blueGrey),
    SocialModel('GeneralWebsite2',
        icon: FontAwesomeIcons.store, colour: Colors.blueGrey),
    SocialModel('GeneralWebsite3',
        icon: FontAwesomeIcons.link, colour: Colors.blueGrey),
    SocialModel('GeneralWebsite4',
        icon: FontAwesomeIcons.poll, colour: Colors.blueGrey),
  ];

  static SocialModel getSocial(String exactName) {
    return socialList.firstWhere(
        (element) => element.name.toLowerCase() == exactName.toLowerCase());
  }
}
