import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'social_model.dart';

class SocialLists {
  static final List<SocialModel> socialList = [
    SocialModel('WhatsApp',
        icon: FontAwesomeIcons.whatsapp, colour: Colors.teal.shade800),
    const SocialModel('Phone',
        icon: FontAwesomeIcons.phoneAlt, colour: Color(0xFF38A45B)),
    SocialModel('Telegram',
        icon: FontAwesomeIcons.telegram, colour: Colors.blue.shade800),
    const SocialModel('Twitter',
        icon: FontAwesomeIcons.twitter, colour: Color(0xFF1da1f2)),
    SocialModel('Instagram',
        icon: FontAwesomeIcons.instagram, colour: Colors.orange.shade700),
    const SocialModel('Tiktok',
        icon: FontAwesomeIcons.tiktok, colour: Color(0xFFEE1D52)),
    const SocialModel('Sms',
        icon: FontAwesomeIcons.sms, colour: Color(0xFFDC722B)),
    const SocialModel('Email',
        icon: FontAwesomeIcons.at, colour: Color(0xFFBB001B)),
    const SocialModel('YouTube',
        icon: FontAwesomeIcons.youtube, colour: Color(0xFFF80000)),
    const SocialModel('Google',
        icon: FontAwesomeIcons.google, colour: Color(0xFFE34133)),
    const SocialModel('Github',
        icon: FontAwesomeIcons.github, colour: Color(0xFF211F1F)),
    const SocialModel('Facebook',
        icon: FontAwesomeIcons.facebookF, colour: Color(0xFF4267B2)),
    const SocialModel('Messenger',
        icon: FontAwesomeIcons.facebookMessenger, colour: Color(0xFF006AFF)),
    const SocialModel('WeChat',
        icon: FontAwesomeIcons.weixin, colour: Color(0xFF7bb32e)),
    SocialModel('LinkedIn',
        icon: FontAwesomeIcons.linkedin, colour: Colors.blue.shade900),
    const SocialModel('GooglePlay',
        icon: FontAwesomeIcons.googlePlay, colour: Color(0xFF40916c)),
    const SocialModel('AppStore ',
        icon: FontAwesomeIcons.appStore, colour: Color(0xFF1F7EF4)),
    const SocialModel('Paypal',
        icon: FontAwesomeIcons.paypal, colour: Color(0xff00457C)),
    const SocialModel('Patreon',
        icon: FontAwesomeIcons.patreon, colour: Color(0xFFFF424D)),
    const SocialModel('Stripe',
        icon: FontAwesomeIcons.stripeS, colour: Color(0xFF4379FF)),
    const SocialModel('Amazon',
        icon: FontAwesomeIcons.amazon, colour: Color(0xFFFF9900)),
    const SocialModel('Snapchat',
        icon: FontAwesomeIcons.snapchatGhost, colour: Colors.black),
    const SocialModel('Medium',
        icon: FontAwesomeIcons.mediumM, colour: Color(0xFF000000)),
    const SocialModel('Pinterest',
        icon: FontAwesomeIcons.pinterestP, colour: Color(0xFFE60023)),
    const SocialModel('WeChat',
        icon: FontAwesomeIcons.weixin, colour: Color(0xFF7bb32e)),
    const SocialModel('Devto',
        icon: FontAwesomeIcons.dev, colour: Color(0xFF000000)),
    const SocialModel('Slack',
        icon: FontAwesomeIcons.slack, colour: Color(0xFF4A154B)),
    const SocialModel('Twitch',
        icon: FontAwesomeIcons.twitch, colour: Color(0xFF6441A4)),
    const SocialModel('Gitlab',
        icon: FontAwesomeIcons.gitlab, colour: Color(0xFFF46A25)),
    const SocialModel('Discord',
        icon: FontAwesomeIcons.discord, colour: Color(0xFF7289DA)),
    const SocialModel('Dribbble',
        icon: FontAwesomeIcons.dribbble, colour: Color(0xFFE34A85)),
    const SocialModel('Steam',
        icon: FontAwesomeIcons.steam, colour: Color(0xFF2a475e)),
    const SocialModel('Tumblr',
        icon: FontAwesomeIcons.tumblr, colour: Color(0xFF35465C)),
    const SocialModel('Behance',
        icon: FontAwesomeIcons.behance, colour: Color(0xFF1666F7)),
    const SocialModel('Shopee',
        icon: FontAwesomeIcons.shoppingBag, colour: Color(0xFFE64A2E)),
    SocialModel('User',
        icon: FontAwesomeIcons.userAlt, colour: Colors.lightGreen.shade700),
    SocialModel('Users',
        icon: FontAwesomeIcons.users, colour: Colors.green.shade700),
    const SocialModel('Blog',
        icon: FontAwesomeIcons.blog, colour: Color(0xFF087E8B)),
    const SocialModel('Blog2',
        icon: FontAwesomeIcons.penAlt, colour: Color(0xFF087E8B)),
    const SocialModel('GeneralWebsite',
        icon: FontAwesomeIcons.globe, colour: Colors.blueGrey),
    const SocialModel('GeneralWebsite2',
        icon: FontAwesomeIcons.store, colour: Colors.blueGrey),
    const SocialModel('GeneralWebsite3',
        icon: FontAwesomeIcons.link, colour: Colors.blueGrey),
    const SocialModel('GeneralWebsite4',
        icon: FontAwesomeIcons.poll, colour: Colors.blueGrey),
  ];

  static SocialModel getSocial(String? exactName) {
    return socialList.firstWhere(
        (element) => element.name.toLowerCase() == exactName!.toLowerCase());
  }
}
